name: Build Firmware

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build Firmware
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Cache PlatformIO Dependencies
        uses: actions/cache@v2
        with:
          path: ~/.platformio
          key: ${{ runner.os }}-pio-${{ hashFiles('**/platformio.ini') }}
          restore-keys: |
            ${{ runner.os }}-pio-

      - name: Set Up PlatformIO
        run: |
          pip install -U platformio
          pio upgrade --dev
          pio update

      - name: Build Firmware
        run: platformio run --environment espwroom32